---
galaxy_info:
  author: Damjan Georgievski
  description: a role that compiles and installs uWSGI
  license: BSD
  min_ansible_version: 1.4
  platforms:
    - name: Ubuntu
      versions:
      - raring
      - saucy
      - trusty
    - name: Debian
      versions:
      - wheezy
    - name: EL
      versions:
      - 6
      - 7
  categories:
    - web
dependencies: []
